spring:
  application:
    name: plusapi
  datasource:
    name: demo05
    url: jdbc:mysql://localhost:3306/demo05
    username: provision
    password: smg123
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true # ??????????????????
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??sql??
    type-aliases-package: cn.mayanan.plusapi.model
  jpa:
    hibernate:
      # ddl-auto: update  # ???????????????????
      ddl-auto: none  # ???????????
    show-sql: true
    open-in-view: false

server:
  port: 8081
